### ISSUE TITLE
Weird graphical glitches since qt5.8

### ISSUE THREAD

**Issue by vdubuisson** [linuxdeepin/qt5integration#2]
Hello,
I'm an archlinux user and since the qt 5.8 update I have weird graphical glitches almost everywhere in deepin (dock, right-click menu, control center, notifications, ...). Do you have any idea where this might come from ?
Here are some examples :
![dock](https://cloud.githubusercontent.com/assets/12423817/23456055/e541f202-feac-11e6-9c52-06f776392bdd.png)
![control_center](https://cloud.githubusercontent.com/assets/12423817/23456057/e543ffb6-feac-11e6-9b4d-f7f097f9d514.png)
![notification](https://cloud.githubusercontent.com/assets/12423817/23456056/e542303c-feac-11e6-9265-29ab5b34c3e8.png)

**Comment by zccrs** [comment]
Hello,
Is there the problem with using kwin window manager?

**Comment by vdubuisson** [comment]
I'd like to tell you but I can't run kwin. For an unknown reason after installing kwin the 'kwin_x11 --replace' command is crashing.

**Comment by zccrs** [comment]
killall deepin-wm-switcher && kwin_x11 --replace

**Comment by vdubuisson** [comment]
Thanks for your reply but I finally leaved Deepin for Openbox. And I think this issue was linked to this one https://github.com/linuxdeepin/developer-center/issues/200
