### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [linuxdeepin/qt5integration#3]
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DXCB_USE_XLIB -DXCB_USE_XINPUT2 -DXCB_USE_SM -DXCB_USE_RENDER -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_PLUGIN -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/include/qtxcb-private -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/libdrm -I/usr/include/qt -I/usr/include/qt/QtOpenGL -I/usr/include/qt/QtWidgets/5.9.0 -I/usr/include/qt/QtWidgets/5.9.0/QtWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtX11Extras -I/usr/include/qt/QtGui/5.9.0 -I/usr/include/qt/QtGui/5.9.0/QtGui -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore/5.9.0 -I/usr/include/qt/QtCore/5.9.0/QtCore -I/usr/include/qt/QtCore -I. -I/usr/include/libdrm -I/usr/lib/qt/mkspecs/linux-g++ -o windoweventhook.o windoweventhook.cpp
windoweventhook.cpp: In member function ‘void deepin_platform_plugin::WindowEventHook::handleFocusInEvent(const xcb_focus_in_event_t*)’:
windoweventhook.cpp:207:83: error: no matching function for call to ‘QXcbConnection::setFocusWindow(QXcbWindow*)’
 cbWindow->connection()->setFocusWindow(static_cast<QXcbWindow *>(w->handle()));
                                                                              ^
In file included from /usr/include/qtxcb-private/qxcbobject.h:43:0,
                 from /usr/include/qtxcb-private/qxcbwindow.h:50,
                 from windoweventhook.h:13,
                 from windoweventhook.cpp:10:
/usr/include/qtxcb-private/qxcbconnection.h:483:10: note: candidate: void QXcbConnection::setFocusWindow(QWindow*)
     void setFocusWindow(QWindow *);
          ^~~~~~~~~~~~~~
/usr/include/qtxcb-private/qxcbconnection.h:483:10: note:   no known conversion for argument 1 from ‘QXcbWindow*’ to ‘QWindow*’
In file included from windoweventhook.cpp:11:0:
vtablehook.h: In instantiation of ‘static bool deepin_platform_plugin::VtableHook::overrideVfptrFun(const typename QtPrivate::FunctionPointer<Func>::Object*, Fun1, const typename QtPrivate::FunctionPointer<Func2>::Object*, Fun2) [with Fun1 = void (QXcbWindowEventListener::*)(const xcb_client_message_event_t*); Fun2 = void (deepin_platform_plugin::WindowEventHook::*)(const xcb_client_message_event_t*); typename QtPrivate::FunctionPointer<Func>::Object = QXcbWindowEventListener; typename QtPrivate::FunctionPointer<Func2>::Object = deepin_platform_plugin::WindowEventHook]’:
windoweventhook.cpp:36:82:   required from here
vtablehook.h:25:32: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         quintptr fun1_offset = *(quintptr *)&fun1;
                                ^~~~~~~~~~~~~~~~~~
vtablehook.h:26:32: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         quintptr fun2_offset = *(quintptr *)&fun2;
                                ^~~~~~~~~~~~~~~~~~
vtablehook.h: In instantiation of ‘static bool deepin_platform_plugin::VtableHook::overrideVfptrFun(const typename QtPrivate::FunctionPointer<Func>::Object*, Fun1, const typename QtPrivate::FunctionPointer<Func2>::Object*, Fun2) [with Fun1 = void (QXcbWindowEventListener::*)(const xcb_focus_in_event_t*); Fun2 = void (deepin_platform_plugin::WindowEventHook::*)(const xcb_focus_in_event_t*); typename QtPrivate::FunctionPointer<Func>::Object = QXcbWindowEventListener; typename QtPrivate::FunctionPointer<Func2>::Object = deepin_platform_plugin::WindowEventHook]’:
windoweventhook.cpp:38:76:   required from here
vtablehook.h:25:32: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         quintptr fun1_offset = *(quintptr *)&fun1;
                                ^~~~~~~~~~~~~~~~~~
vtablehook.h:26:32: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         quintptr fun2_offset = *(quintptr *)&fun2;
                                ^~~~~~~~~~~~~~~~~~
vtablehook.h: In instantiation of ‘static bool deepin_platform_plugin::VtableHook::overrideVfptrFun(const typename QtPrivate::FunctionPointer<Func>::Object*, Fun1, const typename QtPrivate::FunctionPointer<Func2>::Object*, Fun2) [with Fun1 = void (QXcbWindowEventListener::*)(xcb_ge_event_t*); Fun2 = void (deepin_platform_plugin::WindowEventHook::*)(xcb_ge_event_t*); typename QtPrivate::FunctionPointer<Func>::Object = QXcbWindowEventListener; typename QtPrivate::FunctionPointer<Func2>::Object = deepin_platform_plugin::WindowEventHook]’:
windoweventhook.cpp:43:76:   required from here
vtablehook.h:25:32: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         quintptr fun1_offset = *(quintptr *)&fun1;
                                ^~~~~~~~~~~~~~~~~~
vtablehook.h:26:32: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         quintptr fun2_offset = *(quintptr *)&fun2;
                                ^~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile.qt5platform-plugin:1248: windoweventhook.o] Error 1
make[1]: Leaving directory '/home/solaraquarion/deepin-qt5integration/src/qt5integration-0.1.8/platformplugin'
make: *** [Makefile:73: sub-platformplug

**Comment by zccrs** [comment]
@SolarAquarion Fixed

**Comment by zccrs** [comment]
Fixed
