### ISSUE TITLE
some non-deepin qt apps have terrible looking

### ISSUE THREAD

**Issue by mrgaturus** [linuxdeepin/qt5integration#30]
here some examples
![Screen Capture_select-area_20200808001756](https://user-images.githubusercontent.com/38407603/89703051-ca97c380-d90c-11ea-8681-3a63fbb62090.png)
![Screen Capture_select-area_20200808002413](https://user-images.githubusercontent.com/38407603/89703135-8953e380-d90d-11ea-8c3b-97d9d8d185f9.png)

**Comment by BLumia** [comment]
qbittorrent now no longer use system Qt theme by default (tested under Arch Linux on DDE).

dolphin (file manager) no longer have white background under dark theme.

Other stuff might still need to be improved, I'll close this one for now, and feel free to create a new issue for other stuff that need to be improved.

Thanks!
