### ISSUE TITLE
[Feature request] Please allow for global menu bars to work

### ISSUE THREAD

**Issue by probonopd** [linuxdeepin/qt5integration#32]
Please allow for global menu bars to work.

E.g., this one:
https://github.com/SeptemberHX/dde-top-panel

Currrently it works for applications like LibreOffice and Chromium but does not work for DDE applications:

![image](https://user-images.githubusercontent.com/2480569/95019855-0da1b900-0668-11eb-9e3a-620173978c37.png)

Reference:
https://github.com/SeptemberHX/dde-top-panel/issues/22

**Comment by xmuli** [comment]
No such plans, at least for the time being (perhaps improvements in this direction will be made later).

For the time being, it is suitable for those who need to customize it (it may not be good enough to force a uniform setting here). So turn it off for now, and turn it back on if it changes later.

**Comment by probonopd** [comment]
@xmuli in case there is an overall Wishlist for Deepin Linux, it would be great if **"global menubar"** could be added to it. I would really like to see such a feature, be it in `qt5integration` or using another technical solution.

Thank you very much for your kind consideration.
