### ISSUE TITLE
qt应用字体被强制替换

### ISSUE THREAD

**Issue by SuperEndermanSM** [linuxdeepin/qt5integration#33]
使用样式表指定字体
在qdesigner可以看到效果
编译后被统一替换成dcontrolcentre设置的字体
暂时没有发现解决方案

问题行为：使用样式表指定字体，被统一替换成dcontrolcentre设置的字体
期望行为：没有样式表的样式被替换为DDE样式，有样式表的控件不替换
感觉DDE的限制比较多了，KDE/Gnome并不会强制替换

另：希望DTK系列也可以自定义样式表

**Comment by xmuli** [comment]
DTK 库在发过程中, 包括 DDE 都是被禁止使用 QSS 样式的.

**Comment by SuperEndermanSM** [comment]
> DTK 库在发过程中, 包括 DDE 都是被禁止使用 QSS 样式的(指内部的开发人员). 所以猜测是是某处的的无意导致的次效果. 后面会使用 qml 写对应的控件, 但是猜测样式表依旧是不会被允许使用的, 也就不会相关的人员去支持. 如果没有其他疑问, 此 issues 下次可能会被关闭

dqt-intergration直接强制替换样式表应该是想要统一dde应用风格吧，可以理解，但是的确给我们的开发带来了困扰，目前只有在DDE下无法正常显示字体
如果QSS不能使用，能否给我们一个解决方案，在DDE下正确使用字体？

**Comment by SuperEndermanSM** [comment]
> DTK 库在发过程中, 包括 DDE 都是被禁止使用 QSS 样式的(指内部的开发人员). 所以猜测是是某处的的无意导致的次效果. 后面会使用 qml 写对应的控件, 但是猜测样式表依旧是不会被允许使用的, 也就不会相关的人员去支持. 如果没有其他疑问, 此 issues 下次可能会被关闭

目前看没有QSS样式的控件会被替换成dtk风格，使用QSS后如背景色，图片都是正常
只有字体挂了

**Comment by SuperEndermanSM** [comment]
已解决
强制替换问题在RC版本以后不能复现了
另一个程序发现是上古时期的代码强制刷新UI把字体刷新没了，修改后问题已经解决
给大佬添麻烦了
