### ISSUE TITLE
QSpinBox up down arrow in one line

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/qt5integration#37]
![alt](https://s3.ax1x.com/2021/03/02/6ivTDf.jpg)
-style fusion
![alt](https://s3.ax1x.com/2021/03/02/6ivbVS.jpg)

**Comment by xmuli** [comment]
图 挂了

**Comment by sonichy** [comment]
图需要梯子

**Comment by xmuli** [comment]
Your question is? This is a pattern for QSpinBox

![image](https://user-images.githubusercontent.com/33887845/109600748-91e56300-7b58-11eb-97e2-80d22d2ebb85.png)

**Comment by sonichy** [comment]
First image fixed.

**Comment by kegechen** [comment]
try setProperty("_d_dtk_spinBox", true);

**Comment by sonichy** [comment]
DTK?

**Comment by BLumia** [comment]
图还是挂了的状态。可以直接在 GitHub Issue 里放图的。

先关掉了。如果这个问题目前还有的话，可以开个新的 issue 反馈哈。
