### ISSUE TITLE
QTableWidget horizontal scrollbar is in the cell (on the right of the horizontal header)

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/qt5integration#38]
The last line of QTableWidget can not display wholy.
![alt](https://s3.ax1x.com/2021/03/02/6ixiaF.png)
-style fusion
![alt](https://ae01.alicdn.com/kf/U99e5555920a2492db87be88cbe66d94dE.jpg)

**Comment by BLumia** [comment]
The images you attached seems no longer available. If this issue still exists in the current codebase, please feel free to create a new issue to report so we can look into it. Thanks!

你附带的图片挂了，如果你原本所想表达的问题在目前最新版本仍然存在的话，可以建个新的 issue 反馈，我们会跟进处理。感谢！
