### ISSUE TITLE
无法获取和设置QPalette

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/qt5integration#40]
![alt](https://ae01.alicdn.com/kf/U6784e485ffc3472789722b4f5a78bb4ec.jpg)

带 -style fusion 参数运行
![alt](https://ae01.alicdn.com/kf/U6b4a8c833dc944f9a6949760abc5950b1.jpg)
```
QPalette palette = ui->pushButton_text_color->palette();
QBrush brush = palette.color(QPalette::ButtonText);
QColor color = QColorDialog::getColor(brush.color(), this);
if (color.isValid()) {
    scene->pen.setColor(color);
    palette.setColor(QPalette::ButtonText, color);
    ui->pushButton_text_color->setPalette(palette);
}
```

**Comment by xmuli** [comment]
设置调色版颜色生效，需要添加如下行
https://github.com/xmuli/lfxNet/blob/241573224c75c6f983e5a96906bb94fa15a1743a/WinSetting.cpp#L56

    ui->labLabTextColor->setAutoFillBackground(true);

**Comment by sonichy** [comment]
无效。

**Comment by xmuli** [comment]
![20210316_102013](https://user-images.githubusercontent.com/33887845/111246445-3a0f2780-8641-11eb-9802-8297f8777c6a.png)

你的 “无效” 两个字有点简洁啊。看你使用的 纯 Qt 的，给你写了一个例子 deam.zip。

[deam.zip](https://github.com/linuxdeepin/qt5integration/files/6145616/deam.zip)

效果如图

![Peek 2021-03-16 10-13](https://user-images.githubusercontent.com/33887845/111246246-df75cb80-8640-11eb-9188-4f47919308f1.gif)

**Comment by sonichy** [comment]
我就知道，我是QPushButton，你是QLabel，你试试QPushButton，嘿嘿嘿。

**Comment by xmuli** [comment]
确实是个 BUG
![image](https://user-images.githubusercontent.com/33887845/111285154-ccccb800-867b-11eb-9a4e-4c925f556d26.png)

**Comment by kegechen** [comment]
由于 chameleon 风格button有渐变的效果， 所以使用的是 QPalette::Light 和 QPalette::Dark 来线性渐变的， 所以可能需要同时设置这俩role才能达到效果。 @sonichy

**Comment by sonichy** [comment]
1.不会设置。
2.不想设置。
