### ISSUE TITLE
This Library Causes All Qt5 Apps to Fail

### ISSUE THREAD

**Issue by droidmonkey** [linuxdeepin/qt5integration#41]
I am going to recommend that all deepin software be removed from Fedora and Manjaro repositories. Your product causes all other Qt5 products (namely Krita, KeePassXC, and OpenRGB) to either crash at startup or have significant problems with keyboard input. You are interfering with other products and that is not good.

**Comment by justforlxz** [comment]
Relax man, if we did something wrong, please tell us and we can modify it. I understand that you have encountered a problem. We did not create this project to destroy other software. I hope you can understand.

**Comment by droidmonkey** [comment]
I was pretty hyped because of the impossible to detect/troubleshoot issues that were caused by deepin-qt5. #4 and #35 represent the major problem, but there are also subtle issues happening in many other qt5 apps such as text edits not working and keyboard input delays or drops. This appears to be an issue with the library packaging because it should not be injecting itself into all qt5 apps, but just deepin apps.

Are you setting Qt env vars that make deepin the default platform provider?

**Comment by justforlxz** [comment]
> I was pretty hyped because of the impossible to detect/troubleshoot issues that were caused by deepin-qt5. #4 and #35 represent the major problem, but there are also subtle issues happening in many other qt5 apps such as text edits not working and keyboard input delays or drops. This appears to be an issue with the library packaging because it should not be injecting itself into all qt5 apps, but just deepin apps.
> 
> Are you setting Qt env vars that make deepin the default platform provider?

We will discuss the new solution. By default, all qt programs should not use dxcb and style.

**Comment by droidmonkey** [comment]
Here are minimal reproduction steps:

1. Install Fedora 33
2. Install keepassxc
3. Install any deepin app
4. Restart the OS
5. Open keepassxc and notice that keyboard input to text fields is lagged and selecting text and typing yields no results. 
6. Install Krita and attempt to launch, it will crash

**Comment by droidmonkey** [comment]
Thank you for looking into this, apologize for the hard introduction.

**Comment by droidmonkey** [comment]
Nice fix! Thank you
