### ISSUE TITLE
Bug report : DTK  CheckBox  Style in QtCreator

### ISSUE THREAD

**Issue by jiangzc** [linuxdeepin/qt5integration#43]
当所有选项都没选中时，不知道 CheckBox  触发区域在哪里。

![image](https://user-images.githubusercontent.com/13901512/115987806-362fd700-a5e9-11eb-9852-ccac11b6fd59.png)

![image](https://user-images.githubusercontent.com/13901512/115987795-29ab7e80-a5e9-11eb-957c-a28f1e56834c.png)

**Comment by kegechen** [comment]
done
