### ISSUE TITLE
Build failure on openSUSE Tumbleweed 

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/qt5integration#44]
reproduce on 5.1.11 and 5.1.12. But  5.1.5 is ok.

[   10s] g++ -Wl,--as-needed -Wl,--no-undefined -fno-access-control -g -Wall -fprofile-arcs -ftest-coverage -O0 -Wl,-O1 -Wl,-rpath,/home/abuild/rpmbuild/BUILD/qt5integration-5.1.12/tests/styleplugins/chameleon/../../../bin/plugins/styles -o tests ut_builtinengine.o ut_qsvgiconengine.o ut_chameleonstyle.o dbuiltiniconengine.o qsvgiconengine.o qsvgiohandler.o chameleonstyle.o main.o qrc_theme-icons.o qrc_icons.o   -lgtest -L/home/abuild/rpmbuild/BUILD/qt5integration-5.1.12/tests/styleplugins/chameleon/../../../bin/plugins/styles -lchameleon /usr/lib64/libdtkwidget.so /usr/lib64/libdtkgui.so /usr/lib64/libQt5PrintSupport.so /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5X11Extras.so /usr/lib64/libQt5Gui.so /usr/lib64/libdtkcore.so /usr/lib64/libQt5DBus.so /usr/lib64/libQt5Xml.so /usr/lib64/libQt5Network.so /usr/lib64/libQt5Concurrent.so /usr/lib64/libQt5Core.so -lGL -lpthread   
[   10s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: cannot find -lchameleon
[   10s] collect2: error: ld returned 1 exit status
[   10s] make[1]: *** [Makefile:199: tests] Error 1
[   10s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/qt5integration-5.1.12/tests'
[   10s] make: *** [Makefile:151: sub-tests-make_first] Error 2
[   10s] make: *** Waiting for unfinished jobs....
[   10s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/qt5integration-5.1.12/iconengineplugins/builtinengine'
[   10s] rm -f libdtkbuiltin.so

**Comment by kegechen** [comment]
try find libchameleon.so  in  /home/abuild/rpmbuild/BUILD/qt5integration-5.1.12/bin/plugins/styles

**Comment by hillwoodroc** [comment]
This is a random occurrence. It does not occur every time. I doubt qmake scripts does not opitimize for multi-thread compiling.

**Comment by hillwoodroc** [comment]
If i rebuild this bailure without any change, it will be success.
https://build.opensuse.org/package/show/X11:Deepin:Factory/qt5integration
![image](https://user-images.githubusercontent.com/1880237/130169859-27fd0334-8377-4f6f-8828-09ed77ea289a.png)

**Comment by BLumia** [comment]
Not sure if this issue still remain on the most recent release of DDE, if it does. please create a new issue report so we can look into it. Thanks!
