### ISSUE TITLE
[bug]QDialog miniheight is 40, not 0

### ISSUE THREAD

**Issue by ZefengWang** [linuxdeepin/qt5integration#48]
the QDialog mini height is set to 40, when I set the number smaller then 40, it doesn't work and set fixed to 40
on UOS

**Comment by ZefengWang** [comment]
https://bbs.deepin.org/zh/post/230278?id=230278&limit=20&offset=0&postId=1291085
from this link

**Comment by kegechen** [comment]
貌似也不是在这个项目下提issue，有可能是窗管限制的。

**Comment by kegechen** [comment]
换成openbox可以设置0高度。so不是此项目导致的问题。
