### ISSUE TITLE
Certain icons missing in QupZilla (qt5 browser)

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [linuxdeepin/qt5integration#5]
![deepinscreenshot_select-area_20170810170436](https://user-images.githubusercontent.com/30905416/29192093-04b0424a-7dee-11e7-8945-ae484d40fc3d.png)

![deepinscreenshot_select-area_20170810165907](https://user-images.githubusercontent.com/30905416/29192094-04b31498-7dee-11e7-8f35-61c7dcade401.png)

As indicated by the photos, icons are missing from QupZilla, such as the home and new tab buttons, that are present in KDE and GNOME. I suspect it has to do with how DDE integrates with Qt5 applications, though I have no idea, only missing icons.

Also, many icons are missing from the Main Menu dropdown, two of which I circled (print icon and "binoculars" for the find command).

These issues are non-vital, but appear to be bugs on DDE's side.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
