### ISSUE TITLE
Could you please add libqt5xcbqpa headers for Qt 5.9.2?

### ISSUE THREAD

**Issue by zhtengw** [linuxdeepin/qt5integration#6]
It will be more convenient to package for other distributions who have upgrade Qt to version 5.9.2, such as Gentoo.

**Comment by hosiet** [comment]
@zhtengw I believe you may find those headers here: https://github.com/linuxdeepin/qt5dxcb-plugin/tree/master/platformplugin/libqt5xcbqpa-dev

**Comment by zhtengw** [comment]
No need anymore.
