### ISSUE TITLE
Window controls not scaled properly in 15.7

### ISSUE THREAD

**Issue by DanyGee** [linuxdeepin/qt5integration#8]
Window controls stopped being properly scaled in Deepin 15.7 for non system apps at 4K and UI scaled x2.
On 15.6 this worked fine - controls were properly scaled for all apps.

The good one...
![photo_2018-08-28_00-01-44](https://user-images.githubusercontent.com/26818551/44733526-10746c00-aae8-11e8-8646-b2b81a5706a7.jpg)

...and the bad one...
![photo_2018-08-28_00-01-50](https://user-images.githubusercontent.com/26818551/44733551-1d915b00-aae8-11e8-9b36-d1a45a037c89.jpg)

Any solution for this?
![bitmoji](https://render.bitstrips.com/v2/cpanel/02919870-550c-48e9-b644-df89ae03584e-fe85af63-ad51-4198-8b90-cb1af6ce89fd-v1.png?transparent=1&palette=1&width=246)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
